### ISSUE TITLE
Threading issues with ST2_2143 and Win XP

### ISSUE THREAD

**Issue by alexandrei** [SublimeText/Mote#2]
Hello, I just recently found Mote (very interested in it), but could not get it to work. I can see it connecting to the server, but when trying to list the files, this is what I get in the console:

``` ...
cd / True
Exception in thread Thread-3:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\Mote.py", line 219, in run
  File ".\Mote.py", line 315, in psftp
  File ".\Mote.py", line 325, in untilprompt
IOError: [Errno 22] Invalid argument 
```

I've tried all types of connection strings - same behavior. Also, putty and all other utilities (psftp, etc) are added to $PATH.

Any ideas what could be the issue?

**Comment by hyperturtle** [comment]
I think the issue is that SublimeText 2 creates its own $PATH. Try copying psftp.exe to the plugin folder. If that's the issue I'll update the readme. If that's not the issue I'll dig further.

**Comment by alexandrei** [comment]
Ok, that fixed the errors (psftp.exe in Mote dir).. but now, except "Connect", no other command works ("Disconnect" does nothing, "View" does not open the file panel - at least I was expecting to view a file panel somewhere..or in the "Mote" commands list..)

**Comment by alexandrei** [comment]
Anayway, this is a second issue, so I am going to close this one for now. Thank you!

**Comment by cklosowski** [comment]
I'm still getting an issue much like this with psftp into the Mote\ directory as stated in the documentation. This is my trace:

cd  True
Exception in thread Thread-1:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\Mote.py", line 219, in run
  File ".\Mote.py", line 315, in psftp
  File ".\Mote.py", line 325, in untilprompt
IOError: [Errno 22] Invalid argument

Any thoughts?

**Comment by cklosowski** [comment]
Never mind now. I walked away, came back and must have just had a syntax error. Everything is working perfectly now. Thanks for a great plugin!
