### ISSUE TITLE
numbers in front of file/dir names in view list

### ISSUE THREAD

**Issue by korgoth** [SublimeText/Mote#3]
I have a strange problem with one of my ssh accounts hosted on dreamhost.com

mote connects ok, but when i go to view files the list populates with all the files and directories prepended a number (mostly 2 digit number). so when i try to cd, mode tries to cd with the number which results in a non existing directory or file.

for example i have a directory called 'cutout', in the list its showing as '45 cutout' and mote tries to do 'cd "45 cutout"' which is not existing.

i found no relation between the prepending number and the file/directory it prepends.

any ideas?

**Comment by hyperturtle** [comment]
Do you have any alias's involving `ls`? I'm thinking that's the issue. The way mote works is that it runs `psftp.exe` and parses the output. I'm not really sure if  `psftp.exe` uses the `ls` command to list files, but I'm thinking that's whats going on here.

**Comment by hyperturtle** [comment]
I just checked in a fix, can you get latest and try again?

**Comment by korgoth** [comment]
nope, its a pure account with no fancy formatting added. i just started psftp.exe manually, connected and tried ls, it lists normally. i tried both my dreamhost ssh and the other one thats working fine with mote. output formatting seems completely identical :-/

**Comment by korgoth** [comment]
Working like a charm now! Thanks for the fix, its really useful plugin.

One suggestion: if it is possible, list all the servers and their optins (connect, view, disconnect etc) in the main goto anything window (ie you push ctrl+shift+p, then just type mote connect and choose a host), i think it will be even more userfriendly that way, although i dont know if it can be achieved :-)

Thanks for the great work!
