### ISSUE TITLE
any OSX/Linux support?

### ISSUE THREAD

**Issue by sergeifilippov** [SublimeText/Mote#6]
any OSX/Linux support?

**Comment by ninjapanzer** [comment]
I was just thinking the same thing. I am going to give it a look and see if it will be easly to hook in

**Comment by aponxi** [comment]
If you need testers on linux, I volunteer ! I use Ubuntu 12.04 64-bit.

**Comment by ninjapanzer** [comment]
Very cool please watch my fork then

**Comment by aponxi** [comment]
watching... Now, to prepare a testing environment I would need a ssh server correct? Can I test it on github server by any chance or should I set up a ssh server on my computer?

**Comment by ninjapanzer** [comment]
That sounds about right. But if you are on Ubuntu you would likely be able to just sftp local host

**Comment by ninjapanzer** [comment]
So I am a little light on python libraries but I am poking around with including paramiko as the posix replacement for putty for now I am directly embedding the modules in the plugin. So far things are progressing. I have an unstable branch with this work in my fork. If any of you python peeps have some advice on my ongoing work it would be appreciate.

**Comment by ninjapanzer** [comment]
I have this working in my branch and have submitted a pull request https://github.com/SublimeText/Mote/pull/8
